### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require()

### ISSUE THREAD

**Issue by kritik** [bluwy/vite-plugin-warmup#3] opened 2023-04-28 04:44 UTC
When I added plugin to vite I get an error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module master/node_modules/vite-plugin-warmup/index.js from master/vite.config.ts not supported.
Instead change the require of index.js in master/vite.config.ts to a dynamic import() which is available in all CommonJS modules.

```

Infrastructure:
bin/vite present?: true
vite_ruby: 3.3.0
vite_rails: 3.0.14
rails: 7.0.4.2
node: v16.20.0
npm: 8.19.4
yarn: 1.22.19
pnpm: 
ruby: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

installed packages:
master
├─┬ @modyfi/vite-plugin-yaml@1.0.4
│ └── vite@4.3.3 deduped
├─┬ @vitejs/plugin-vue2@2.2.0
│ └── vite@4.3.3 deduped
├─┬ vite-plugin-environment@1.1.3
│ └── vite@4.3.3 deduped
├─┬ vite-plugin-ruby@3.2.1
│ └── vite@4.3.3 deduped
├─┬ vite-plugin-warmup@0.1.0
│ └── vite@4.3.3 deduped
└── vite@4.3.3

**Comment by bluwy** [comment] 2023-04-28 04:56
Duplicate of https://github.com/bluwy/vite-plugin-warmup/issues/2#issuecomment-1519595598

**Closed as not planned by bluwy** 2023-04-28 04:56 UTC
